server:
  port: 8081

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  hibernate:
    ddl-auto: none
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/super_mailer
    username: postgres
    password: superspring125!
    schema: public
    initialize: true
    initialization-mode: always
    continue-on-error: true